project/users/forms.py
# project/users/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtform.validators import DataRequired, Length, EqualTo, Email


class RegistrationForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])

project/__init__.py
# Imports
from flask import Flask

## Config
#app = Flask(__name__)
#print(app)
#from . import views

# Configuration with Blueprint
app = Flask(__name__, instance_relative_config=True)
app.config.from_pyfile('flask.cfg')

# Blueprints in the project
from project.users.views import users_blueprint

# Register the blueprints
app.register_blueprint(users_blueprint)

project/users/views.py
from flask import render_template, Blueprint
from flask import request

#from . import User
from project.users import users
from project.users import forms

users_blueprint = Blueprint('users', __name__, template_folder='templates')

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering!', 'success')
                return redirect(url_for('users.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    #return render_template('register.html', form=form)
    flash("Testing")
    print("tee")
    return render_template('index.html')

project/views.py
from . import app
from flask import render_template

@app.route('/')
def index():
    return render_template('index.html')

# @app.route('/register')
# def register():
#    pass

@app.route('/login')
def login():
    return("Login Page")

@app.route('/dashboard')
def dashboard():
    return("Dashboard")

project/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Login App">
    <meta name="author" content="nsprams@gmail.com">
    <title>Login test app</title>
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>
 
<h1>Login and Upload!</h1>
 
 
 
This is a test website that I will be working on to create a working login app:
 
 
<h2>Login REST API</h2>
 
 
<h2>Upload a file</h2>
 
  </body>
</html>

project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
<div class="user-registration">
  <div class="page-header">
    <h2>Please Register Your New Account</h2>
  </div>
<form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
      {{ render_field(form.confirm, placeholder="Confirm password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create New Account</button>
  </form>
</div>
 
{% endblock %}